# Generated by Django 3.0.8 on 2020-08-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
